In [29]:
# importing all  necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [76]:
# bringing my csv files into use
train_feature=pd.read_csv('/content/drive/MyDrive/hackathon/training_set_features.csv')
test_feature=pd.read_csv('/content/drive/MyDrive/hackathon/test_set_features.csv')
train_set_labels=pd.read_csv('/content/drive/MyDrive/hackathon/training_set_labels.csv')

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [49]:
# concatinating just my target to features and removing the columns with very less values and filling the float col with their median
train_fin=pd.concat([train_feature,train_set_labels.loc[:,['xyz_vaccine','seasonal_vaccine']]],axis=1)
train_fin.drop(columns=['employment_occupation','employment_industry','health_insurance','income_poverty'],axis=1,inplace=True)
reqcol=train_fin.loc[:,'xyz_concern':'opinion_seas_sick_from_vacc']
for col in reqcol:
    if(train_feature[col].isna().any()):
        mean_val=train_fin[col].median()
        train_feature[col].fillna(mean_val,inplace=True)

In [50]:
#dropping row with mising values in object data types
train_fin = train_fin.dropna(how='any',axis=0)

In [51]:
###performing one hot encoder to it
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
categorical_cols=['age_group','education','race','sex','marital_status','rent_or_own','employment_status','hhs_geo_region','census_msa']
encoded_cols=encoder.fit_transform(train_fin[categorical_cols])
encoded_cols_df=pd.DataFrame(encoded_cols.toarray(),columns=encoder.get_feature_names_out(categorical_cols))
train_fin.reset_index(drop=True,inplace=True)
train_encoded=pd.concat([train_fin,encoded_cols_df],axis=1)
train_encoded.drop(columns=categorical_cols,axis=1,inplace=True)

In [34]:
train_encoded.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
2              3          1.0            1.0                        0.0   
3              4          2.0            1.0                        0.0   
4              5          3.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
2                   1.0                   0.0                    1.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
2                          1.0                      0.0   
3                          1.0                      0.0   
4                          0.0                      0.0   

   behavioral_touch_face  doctor_recc_xyz  doctor_recc_seasonal  \
0                    1.0              0.0                   0.0   
1                    1.0              0.0                   0.0   
2                    0.0              0.0                   1.0   
3                    1.0              0.0                   0.0   
4                    1.0              0.0                   1.0   

   chronic_med_condition  child_under_6_months  health_worker  \
0                    0.0                   0.0            0.0   
1                    0.0                   0.0            0.0   
2                    1.0                   0.0            0.0   
3                    0.0                   0.0            0.0   
4                    0.0                   0.0            0.0   

   opinion_xyz_vacc_effective  opinion_xyz_risk  opinion_xyz_sick_from_vacc  \
0                         3.0               1.0                         2.0   
1                         5.0               4.0                         4.0   
2                         3.0               3.0                         5.0   
3                         3.0               3.0                         2.0   
4                         5.0               2.0                         1.0   

   opinion_seas_vacc_effective  opinion_seas_risk  \
0                          2.0                1.0   
1                          4.0                2.0   
2                          5.0                4.0   
3                          3.0                1.0   
4                          5.0                4.0   

   opinion_seas_sick_from_vacc  household_adults  household_children  \
0                          2.0               0.0                 0.0   
1                          4.0               0.0                 0.0   
2                          1.0               0.0                 0.0   
3                          4.0               1.0                 0.0   
4                          4.0               2.0                 3.0   

   xyz_vaccine  seasonal_vaccine  age_group_18 - 34 Years  \
0            0                 0                      0.0   
1            0                 1                      0.0   
2            0                 1                      0.0   
3            0                 0                      0.0   
4            0                 0                      0.0   

   age_group_35 - 44 Years  age_group_45 - 54 Years  age_group_55 - 64 Years  \
0                      0.0                      0.0                      1.0   
1                      1.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      1.0     

In [52]:
new_drop=['household_children','age_group_18 - 34 Years','age_group_35 - 44 Years','age_group_45 - 54 Years','education_12 Years','education_< 12 Years','education_Some College','race_Black','race_Hispanic','race_Other or Multiple','sex_Male','marital_status_Not Married','rent_or_own_Rent','employment_status_Unemployed','hhs_geo_region_dqpwygqj','hhs_geo_region_oxchjgsf','hhs_geo_region_qufhixun','census_msa_MSA, Principle City']
train_encoded.drop(columns=new_drop,axis=1,inplace=True)

In [11]:
train_encoded.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
2              3          1.0            1.0                        0.0   
3              4          2.0            1.0                        0.0   
4              5          3.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
2                   1.0                   0.0                    1.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
2                          1.0                      0.0   
3                          1.0                      0.0   
4                          0.0                      0.0   

   behavioral_touch_face  doctor_recc_xyz  doctor_recc_seasonal  \
0                    1.0              0.0                   0.0   
1                    1.0              0.0                   0.0   
2                    0.0              0.0                   1.0   
3                    1.0              0.0                   0.0   
4                    1.0              0.0                   1.0   

   chronic_med_condition  child_under_6_months  health_worker  \
0                    0.0                   0.0            0.0   
1                    0.0                   0.0            0.0   
2                    1.0                   0.0            0.0   
3                    0.0                   0.0            0.0   
4                    0.0                   0.0            0.0   

   opinion_xyz_vacc_effective  opinion_xyz_risk  opinion_xyz_sick_from_vacc  \
0                         3.0               1.0                         2.0   
1                         5.0               4.0                         4.0   
2                         3.0               3.0                         5.0   
3                         3.0               3.0                         2.0   
4                         5.0               2.0                         1.0   

   opinion_seas_vacc_effective  opinion_seas_risk  \
0                          2.0                1.0   
1                          4.0                2.0   
2                          5.0                4.0   
3                          3.0                1.0   
4                          5.0                4.0   

   opinion_seas_sick_from_vacc  household_adults  xyz_vaccine  \
0                          2.0               0.0            0   
1                          4.0               0.0            0   
2                          1.0               0.0            0   
3                          4.0               1.0            0   
4                          4.0               2.0            0   

   seasonal_vaccine  age_group_55 - 64 Years  age_group_65+ Years  \
0                 0                      1.0                  0.0   
1                 1                      0.0                  0.0   
2                 1                      0.0                  1.0   
3                 0                      0.0                  0.0   
4                 0                      0.0                  1.0   

   education_College Graduate  race_White  sex_Female  marital_status_Married  \
0                         0.0         1.0         1.0                     0.0   
1                         0.0         1.0         0.0                     0.0   
2                         0.0         1.0         1.0                     0.0   
3                         0.0         1.0     

In [36]:
#using logistic regression (will using this  model just for xyz vaccine)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
X=train_encoded.drop(columns=['xyz_vaccine','seasonal_vaccine'])
y=train_fin['xyz_vaccine']
###splitting dataset into training test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model=LogisticRegression(max_iter=1000,random_state=42,penalty='l1', solver='liblinear', C=1.0)
model.fit(X_train,y_train)


LogisticRegression(max_iter=1000, penalty='l1', random_state=42,
                   solver='liblinear')

In [37]:
from sklearn.metrics import roc_auc_score
y_pred=model.predict_proba(X_test)[:,1]
roc_auc_score(y_test,y_pred)

0.8425043572526645

In [23]:
y_pred

array([0.12245622, 0.09489466, 0.10276983, ..., 0.21975833, 0.10079651,
       0.10297537])

In [38]:
##seasonal regularisation()
model2=LogisticRegression(max_iter=1000,random_state=42,penalty='l1', solver='liblinear', C=1.0)
X=train_encoded.drop(columns=['xyz_vaccine','seasonal_vaccine'])
y=train_fin['seasonal_vaccine']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model2.fit(X_train,y_train)
y_pred=model2.predict_proba(X_test)[:,1]

In [19]:
roc_auc_score(y_test,y_pred)

0.8508873328808207

In [26]:
y_pred

array([0.13729229, 0.25202862, 0.14116462, ..., 0.31733141, 0.21932801,
       0.92455869])

In [79]:
#now using this for our test data and submitting it
test_feature.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0          26707          2.0            2.0                        0.0   
1          26708          1.0            1.0                        0.0   
2          26709          2.0            2.0                        0.0   
3          26710          1.0            1.0                        0.0   
4          26711          3.0            1.0                        1.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   1.0                   0.0                    1.0   
1                   0.0                   0.0                    0.0   
2                   0.0                   1.0                    1.0   
3                   0.0                   0.0                    0.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          1.0                      0.0   
1                          0.0                      0.0   
2                          1.0                      1.0   
3                          0.0                      0.0   
4                          1.0                      1.0   

   behavioral_touch_face  doctor_recc_xyz  doctor_recc_seasonal  \
0                    1.0              0.0                   0.0   
1                    0.0              0.0                   0.0   
2                    1.0              0.0                   0.0   
3                    0.0              1.0                   1.0   
4                    1.0              0.0                   0.0   

   chronic_med_condition  child_under_6_months  health_worker  \
0                    0.0                   0.0            0.0   
1                    0.0                   0.0            0.0   
2                    0.0                   0.0            0.0   
3                    1.0                   0.0            0.0   
4                    0.0                   0.0            1.0   

   health_insurance  opinion_xyz_vacc_effective  opinion_xyz_risk  \
0               1.0                         5.0               1.0   
1               0.0                         4.0               1.0   
2               NaN                         5.0               4.0   
3               1.0                         4.0               2.0   
4               1.0                         5.0               2.0   

   opinion_xyz_sick_from_vacc  opinion_seas_vacc_effective  opinion_seas_risk  \
0                         1.0                          5.0                1.0   
1                         1.0                          4.0                1.0   
2                         2.0                          5.0                4.0   
3                         2.0                          4.0                4.0   
4                         4.0                          4.0                4.0   

   opinion_seas_sick_from_vacc      age_group         education      race  \
0                          1.0  35 - 44 Years  College Graduate  Hispanic   
1                          1.0  18 - 34 Years          12 Years     White   
2                          4.0  55 - 64 Years  College Graduate     White   
3                          2.0      65+ Years          12 Years     White   
4                          2.0  35 - 44 Years          12 Years     Black   

      sex             income_poverty marital_status rent_or_own  \
0  Female                  > $75,000    Not Married        Rent   
1    Male              Below Poverty    Not Married        Rent   
2    Male                  > $75,000        Married         Own   
3  Female  <= $75,000, Above Poverty        Married         Own   
4  Female  <= $75,000, Above Poverty    Not Married         Own   

    employment_status hhs_geo_region                census_msa  \
0            Employed       mlyzmhmf  MSA, Not Principle  City   
1            Employed       bhuqouqj                   Non-MSA   
2   

In [81]:
test_feature.drop(columns=['employment_occupation','employment_industry','health_insurance','income_poverty'],axis=1,inplace=True)
reqcol=test_feature.loc[:,'xyz_concern':'opinion_seas_sick_from_vacc']
for col in reqcol:
    if(train_feature[col].isna().any()):
        mean_val=test_feature[col].median()
        test_feature[col].fillna(mean_val,inplace=True)
test_feature = test_feature.dropna(how='any',axis=0)

In [82]:
fp_on = pd.DataFrame(test_feature['respondent_id'])
fp_on.head()

respondent_id
0          26707
1          26708
2          26709
3          26710
4          26711

In [83]:
###performing one hot encoder to it
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
categorical_cols=['age_group','education','race','sex','marital_status','rent_or_own','employment_status','hhs_geo_region','census_msa']
encoded_cols=encoder.fit_transform(test_feature[categorical_cols])
encoded_cols_df=pd.DataFrame(encoded_cols.toarray(),columns=encoder.get_feature_names_out(categorical_cols))
test_feature.reset_index(drop=True,inplace=True)
test_encoded=pd.concat([test_feature,encoded_cols_df],axis=1)
test_encoded.drop(columns=categorical_cols,axis=1,inplace=True)

In [84]:
new_drop=['household_children','age_group_18 - 34 Years','age_group_35 - 44 Years','age_group_45 - 54 Years','education_12 Years','education_< 12 Years','education_Some College','race_Black','race_Hispanic','race_Other or Multiple','sex_Male','marital_status_Not Married','rent_or_own_Rent','employment_status_Unemployed','hhs_geo_region_dqpwygqj','hhs_geo_region_oxchjgsf','hhs_geo_region_qufhixun','census_msa_MSA, Principle City']
test_encoded.drop(columns=new_drop,axis=1,inplace=True)

In [85]:
test_encoded.drop(columns=['xyz_vaccine','seasonal_vaccine'],axis=1,inplace=True)

KeyError: "['xyz_vaccine', 'seasonal_vaccine'] not found in axis"

In [87]:
test_encoded.isnull().sum()

respondent_id                           0
xyz_concern                             0
xyz_knowledge                           0
behavioral_antiviral_meds               0
behavioral_avoidance                    0
behavioral_face_mask                    0
behavioral_wash_hands                   0
behavioral_large_gatherings             0
behavioral_outside_home                 0
behavioral_touch_face                   0
doctor_recc_xyz                         0
doctor_recc_seasonal                    0
chronic_med_condition                   0
child_under_6_months                    0
health_worker                           0
opinion_xyz_vacc_effective              0
opinion_xyz_risk                        0
opinion_xyz_sick_from_vacc              0
opinion_seas_vacc_effective             0
opinion_seas_risk                       0
opinion_seas_sick_from_vacc             0
household_adults                        0
age_group_55 - 64 Years                 0
age_group_65+ Years               

In [88]:
z=model.predict_proba(test_encoded)[:,1]
z

array([0.07827621, 0.05143795, 0.46265775, ..., 0.13435228, 0.05965828,
       0.50909006])

In [89]:
p=model2.predict_proba(test_encoded)[:,1]
p

array([0.21249888, 0.05643276, 0.64262603, ..., 0.21973709, 0.31358363,
       0.41082284])

In [90]:
fp_on['xyz_vaccine']=z
fp_on['seasonal_vaccine']=p

In [91]:
fp_on.head()

respondent_id  xyz_vaccine  seasonal_vaccine
0          26707     0.078276          0.212499
1          26708     0.051438          0.056433
2          26709     0.462658          0.642626
3          26710     0.481424          0.885599
4          26711     0.202400          0.509707

In [92]:
fp_on.to_csv('submission.csv',index=False)